---
title: "Fiona"
author: "Fiona Miller"
date: "April 26, 2017"
output: html_document
---

```{r, message = FALSE}
url<-"http://wsgw.mass.gov/data/gispub/shape/contours5k/hp214.zip"
download.file(url,destfile=basename(url))
unzip("hp214.zip",exdir="northampton")
library(macleish)
library(leaflet)
library(rgeos)
library(sp)
```

```{r}
## Buffer for stream (200 ft)
proj4_aea <- "+proj=aea +lat_1=29.5 +lat_2=42.5 +lat_0=37.5 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs"
stream <- macleish_layers[["streams"]] %>%
  spTransform(CRS(proj4_aea)) %>%
  gBuffer(width = 60.96) %>%
  spTransform("+init=epsg:4326")
```

```{r}
## Buffer on Challenge courses (500 ft)
challenge <- macleish_layers[["challenge_courses"]] %>%
  spTransform(CRS(proj4_aea)) %>%
  gBuffer(width = 152.4) %>%
  spTransform("+init=epsg:4326")
```

```{r}
## Buffer on research projects (500ft)
research <- macleish_layers[["research"]] %>%
  spTransform(CRS(proj4_aea)) %>%
  gBuffer(width = 152.4) %>%
  spTransform("+init=epsg:4326")
```


```{r}
names(macleish_layers)
```

```{r}
##Plotting all the buffers.
plot(stream)
plot(challenge)
plot(research)
```

werrrrrrrrrrrrwerwerwerwerwrwerewr


