---
title: "Starry"
author: "Starry Zhou"
date: "4/26/2017"
output: html_document
---

```{r}
url<-"http://wsgw.mass.gov/data/gispub/shape/contours5k/hp214.zip"
download.file(url,destfile=basename(url))
unzip("hp214.zip",exdir="northampton")
```
```{r, message = FALSE}
library(macleish)
library(leaflet)
library(rgeos)
library(sp)
```

```{r}
library(rgdal)
dsn<-path.expand("northampton")
dsn
list.files(dsn)
```

```{r}
orgListLayers(dsn)
```

```{r}
install.packages("macleish")
```

```{r}
library(macleish)
```


```{r}
names(macleish_layers)
```

```{r}
leaflet() %>%
  addTiles() %>%
  addPolygons(data = macleish_layers[["buildings"]], 
              weight = 1, popup = ~ name) %>%
  addPolygons(data = macleish_layers[["forests"]], 
              weight = 1, fillOpacity = 0.2, popup = ~ Sheet1__Na) %>%
  addMarkers(lng = ~long, lat = ~lat, data = sites,
    popup = ~name) %>%
  addPolygons(data = challenge) %>%
  addCircles(lat = 42.448013, lng = -72.680663, radius = 804.672,color="green") %>%
  addPolygons(data= research)
```
```{r}
library(leaflet)
leaflet() %>%
  addTiles() %>%
  addPolylines(data = macleish_layers[["streams"]], 
               weight = 1, color = "red") %>%
  addPolygons(data = stream) 
```












